export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export const SEARCH_SONGS = 'SEARCH_SONGS';
export const SEARCH_SONGS_FAIL = 'SEARCH_SONGS_FAIL';
export const SEARCH_SONGS_SUCCESS = 'SEARCH_SONGS_SUCCESS';

export const SELECT_SONG = 'SELECT_SONG';

export const LOADING_MUSIC = 'LOADING_MUSIC';
