export {
	setSearchTerm,
	selectEntityType,
	searchMusic,
	searchMusicFail,
	searchMusicSuccess,
	searchArtists,
	searchArtistsFail,
	searchArtistsSuccess,
	searchAlbums,
	searchAlbumsFail,
	searchAlbumsSuccess,
	searchSongs,
	searchSongsFail,
	searchSongsSuccess,
	selectArtist,
	selectAlbum,
	selectSong,
	loadingMusic,
} from './music';
